### ISSUE TITLE
SelfSignCert as a charm library

### ISSUE THREAD

**Issue by davigar15** [charmed-kubernetes/kubernetes-dashboard-operator#3]
Hello @jnsgruk,

I find really interesting the class for generating a self sign certificate, and I think many other charms could benefit from it.

Would you consider publishing it as a charm library in Charmhub?

**Comment by jnsgruk** [comment]
Hi @davigar15,

Sure can, I'll take a look some time this week!

**Comment by jnsgruk** [comment]
Done! Check it out [Charmhub](https://charmhub.io/jnsgruk-kubernetes-dashboard/libraries/cert)

I've also added some unit tests for the cert generator: https://github.com/jnsgruk/charm-kubernetes-dashboard/blob/main/tests/unit/test_certs.py
