### ISSUE TITLE
Add full tls-support

### ISSUE THREAD

**Issue by cjohnston1158** [charmed-kubernetes/kubernetes-dashboard-operator#72]
Currently the dashboard only provides support for self signed certs. It would be great if the dashboard could use valid certs.

**Comment by jnsgruk** [comment]
Ack. Just leaving some notes here from our conversation earlier:

It needs a couple of things in reality:

- support for the new [ingress](https://charmhub.io/traefik-k8s/libraries/ingress) relation
- support for the [tls-certificates](https://charmhub.io/tls-certificates-interface/libraries/tls_certificates) relation

**Comment by addyess** [comment]
With [this merge](https://github.com/charmed-kubernetes/kubernetes-dashboard-operator/pull/80), this charm now will support TLS certificates via the telco tls-certificates relation or the legacy easyrsa/vault relation

**Comment by addyess** [comment]
Ingress support via https://github.com/charmed-kubernetes/kubernetes-dashboard-operator/pull/81
